install:
    - make
    - cmake
     # Pip cannot install Conan without these upgrades
    - python3 -m pip install --upgrade pip setuptools
    # Install Conan and CMake >= 3.15
    - python3 -m pip install conan cmake

  # Fail if we can't run Conan.
    - conan --version

compiler:
    - clang
    - gcc

script:
    - mkdir build
    - cd build
    - cmake ..
    - make 
    - bin/unit-tests
